### PR TITLE
Dependency visitor added, fixes #47

### LINKED ISSUE #47: Add a dependency visitor
#48 would solve this 
(not sure why this issue didn't pick up on it)

### PR DESCRIPTION
**Pull request by modulovalue**

### CODE REVIEW

**Comment by kevmoo** [comment]
What problem are you trying to solve here?

CC @jakemac53

**Comment by modulovalue** [comment]
I'm trying to answer questions that depend on the identity of dependencies (e.g. choosing the correct flutter widget). 

Well, obviously an `if is` check would also get the job done but it would either introduce bugs when new dependencies were to be added or a utility class would have to be created (but one shouldn't) because a visitor cleanly solves that problem and moves the responsibility of broadcasting which `Dependency` subclasses exist to the package..

**Comment by jakemac53** [comment]
I think this could pretty easily be implemented outside of this package, and that is probably the ideal solution here. We don't really want extra complexity and/or api surface area?

As a concrete example of that, if we want to add a new dependency type with the current API, that isn't a breaking change. If we introduce this new API then that would be a breaking change.

**Comment by modulovalue** [comment]
@jakemac53 

>If we introduce this new API then that would be a breaking change.

A visitor doesn't exclude a solution with instanceof. But without a visitor one has to introduce a fallback case. 

```dart

import 'package:pubspec_parse/pubspec_parse.dart' as pubspec;

class DependencyTile extends StatelessWidget {
  final pubspec.Dependency dependency;

  const DependencyTile(this.dependency);

  @override
  Widget build(BuildContext context) {
    return dependency.visit(
      pubspec.DependencyVisitor<Widget>.create(
        gitDependency: (pubspec.GitDependency dep) {
          return Container(); // some widget
        },
        hostedDependency: (pubspec.HostedDependency dep) {
          return Container(); // some widget
        },
        pathDependency: (pubspec.PathDependency dep) {
          return Container(); // some widget
        },
        sdkDependency: (pubspec.SdkDependency dep) {
          return Container(); // some widget
        },
      ),
    );
  }
}

T instanceOfDependencyVisitor<T>(
    pubspec.Dependency dependency,
    T Function(pubspec.GitDependency) git,
    T Function(pubspec.HostedDependency) hosted,
    T Function(pubspec.PathDependency) path,
    T Function(pubspec.SdkDependency) sdk,
    T Function() unknown) {
  if (dependency is pubspec.GitDependency) {
    return git(dependency);
  } else if (dependency is pubspec.HostedDependency) {
    return hosted(dependency);
  } else if (dependency is pubspec.PathDependency) {
    return path(dependency);
  } else if (dependency is pubspec.SdkDependency) {
    return sdk(dependency);
  } else {
    return unknown();
  }
}
```

In the case of `DependencyTile` I'd want a new dependency to be a breaking change for the same reason that switch statements with enums are exhaustive by default. The analyzer notifies the programmer that a new case has been added and no fallback case has to be considered.

I do not think `instanceOfDependencyVisitor` is a cleaner solution and would greatly appreciate a comment on the provided example.

**Comment by kevmoo** [comment]
I think the use case is cool, but I think this is functionality that's best left for an end-user to add where they're using this package.

**Comment by modulovalue** [comment]
> I think the use case is cool, but I think this is functionality that's best left for an end-user to add where they're using this package.

@kevmoo I'm sorry if I'm missing something, but the whole point of this pull request is to make that possible in a clean way. A visitor is exactly meant to solve the problem of adding new functionality to classes that can't be changed by the end-user. `is` checks should only be the last resort for when API's cannot be changed by the end-user. 

And even if `is` checks were to be used, they are not exhaustive which can only be achieved using a visitor. 

More on that: [Bob Nystrom: Solving the Expression Problem](https://journal.stuffwithstuff.com/2010/10/01/solving-the-expression-problem/) & [UncleBob: VisitorVersusInstanceOf](http://butunclebob.com/ArticleS.UncleBob.VisitorVersusInstanceOf)

I'll gladly accept your decision that this pull request is unnecessary but it's impossible to map dependencies in an exhaustive way without a visitor and I _need_ a new dependency to be a breaking change even if highly unlikely. These two things cannot be added by a consumer of this package.

**Pull request closed without merging**
